"""create tracks table

Revision ID: 89d634b5d9a6
Revises: 98a9cadb0401
Create Date: 2026-06-15 17:22:14.137738

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89d634b5d9a6'
down_revision: Union[str, Sequence[str], None] = '98a9cadb0401'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tracks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tape_id', sa.Integer(), nullable=False),
    sa.Column('spotify_track_id', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('artist', sa.String(length=255), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=False),
    sa.Column('side', sa.Enum('A', 'B', name='trackside'), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tape_id'], ['tapes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    op.drop_table('tracks')
    op.execute("DROP TYPE IF EXISTS trackside")
